baseURL = "https://jmp0xf.com"
title = "JMP0XF"
description = "JMP0XF's Blog"
theme = "er"

languageCode = "zh-hans"
defaultContentLanguage = "zh-hans"
hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
enableRobotsTXT = true
enableEmoji = true

googleAnalytics = "UA-96139490-1"
disqusShortname = "jmp0xf"

[author]
  name = "jmp0xf"
  homepage = "https://jmp0xf.com"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
