baseURL = "https://kidding.im"
title = "奇丁有术"
theme = "er"

languageCode = "zh-hans"
defaultContentLanguage = "zh-hans"
hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
enableRobotsTXT = true
enableEmoji = true

googleAnalytics = "UA-96139490-1"
disqusShortname = "jmp0xf"

[[menu.main]]             # config your menu              # 配置目录
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[author]
  name = "奇丁"
  homepage = "https://kidding.im"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  showTagCloud = false
  description = "奇丁有术，关注一切好玩的东西"
  since = "2017"            # Site creation time
  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"
