baseURL = "https://jmp0xf.com"
title = "JMP0XF"
theme = "er"

languageCode = "zh-hans"
defaultContentLanguage = "zh-hans"
hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
enableRobotsTXT = true
enableEmoji = true

googleAnalytics = "UA-96139490-1"
disqusShortname = "jmp0xf"

[author]
  name = "JMP0XF"
  homepage = "https://jmp0xf.com"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  showTagCloud = false
  description = "JMP0XF's Blog"
  since = "2017"            # Site creation time
  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"
